general {
    # dbus/sysd lock command (loginctl lock-session)
    lock_cmd = pidof hyprlock || hyprlock               # avoid starting multiple hyprlock instances.
    # before_sleep_cmd = loginctl lock-session          # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on          # command ran after sleep
    inhibit_sleep = 2                                   #
    ignore_dbus_inhibit = false                         # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false                      # whether to ignore systemd-inhibit --what=idle inhibitors
}

# if the screen is locked, wait only 30 seconds and turn off the screen
listener {
    timeout = 30
    on-timeout = bash -c "if pgrep -x hyprlock >/dev/null; then hyprctl dispatch dpms off; fi" # set monitor backlight to minimum
    on-resume = bash -c "if pgrep -x hyprlock >/dev/null; then hyprctl dispatch dpms on; fi" # monitor backlight restore.
}

# Otherwise
listener {
    timeout = 300
    on-timeout = bash -c "if ! pgrep -x hyprlock >/dev/null; then brightnessctl -s set 10%; fi"
    on-resume = bash -c "if ! pgrep -x hyprlock >/dev/null; then brightnessctl -r; fi"
}

# # Lock the screen
# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session
# }

# # Turn off screen
# listener {
#     timeout = 30
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }

# Suspend the system if the screen is locked
listener {
    timeout = 600
    on-timeout = bash -c "if pgrep -x hyprlock >/dev/null; then systemctl suspend; fi"
}