# Autostart necessary processes (like notifications daemons, status bars, etc.)
# user auth
exec-once = systemctl --user start hyprpolkitagent
# notifications
exec-once = swaync
# clipboard manager
exec-once = wl-clip-persist --clipboard regular
# wallpaper
exec-once = systemctl --user start hyprpaper.service
# Sunlight management
exec-once = sunsetr
# Idle management
exec-once = systemctl --user start hypridle.service
# backlighit control
exec-once = systemctl --user start light_ctrl.service
# folder sync control
exec-once = systemctl --user start rclone-sync.timer
exec-once = systemctl --user start rclone-sync.service
# panels and bars
exec-once = waybar
# Or execute your favorite apps at launch like this:
exec-once = betterbird
exec-once = whatsit
exec-once = [workspace 1 silent] $browser
exec-once = [workspace 2 silent] gtk-launch notion
