general {
    # dbus/sysd lock command (loginctl lock-session)
    lock_cmd = pidof hyprlock || hyprlock               # avoid starting multiple hyprlock instances.
    on_lock_cmd = sleep 30 && hyprctl dispatch dpms off # turn off screen after 30 seconds of inactivity, while locked.
    # before_sleep_cmd = loginctl lock-session          # lock before suspend
    after_sleep_cmd = hyprctl dispatch dpms on          # command ran after sleep
    inhibit_sleep = 2                                   #
    ignore_dbus_inhibit = false                         # whether to ignore dbus-sent idle-inhibit requests (used by e.g. firefox or steam)
    ignore_systemd_inhibit = false                      # whether to ignore systemd-inhibit --what=idle inhibitors
}

listener {
    timeout = 300
    on-timeout = brightnessctl -s set 10 # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r         # monitor backlight restore.
}

# # Lock the screen
# listener {
#     timeout = 300
#     on-timeout = loginctl lock-session
# }

# # Turn off screen
# listener {
#     timeout = 30
#     on-timeout = hyprctl dispatch dpms off
#     on-resume = hyprctl dispatch dpms on
# }

# # Suspend the system
# listener {
#     timeout = 600
#     on-timeout = systemctl suspend
# }